dbt_modeling:
  outputs:
    dev:
      dbname: dev
      host: de-c4w4a1-redshift-cluster.cwc4vmzfehfq.us-east-1.redshift.amazonaws.com
      password: Defaultuserpwrd1234+
      port: 5439
      schema: deftunes_serving
      threads: 1
      type: redshift
      user: defaultuser
  target: dev