version: 2

models: 
  - name: sales_per_country_vw
    description: "Sales per country view"
    columns: 
      - name: session_month
      - name: session_year
      - name: country_code
      - name: total_sales
  - name: sales_per_artist_vw
    description: "Sales per artist view"
    columns: 
      - name: session_year
      - name: artist_name
      - name: total_sales
